### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by manparvesh** [IdeaTrackerPlus/IdeaTrackerPlus#30]

**Comment by naushad-madakiya** [comment]
I have occurred and issue with Samsung device OS 5.0.1, The Idea item is with white background and the screenshot you have attached is with dark background

And in Xioami OS 6.0.1, When DarkMode is enabled All UI seems proper, but when dark mode is disabled Idea Item stays in DarkMode

After some more digging I found that issue is with RecyclerView, When we change theme mode all the other UI is recreated except the RecyclerView. If you kill and open the app changes are applied

**Comment by naushad-madakiya** [comment]
- [x] Finish and restart activity instead of Recreate in `MainActivity#changeDarkTheme`, Fix idea item theme update when changing the dark mode.
- [x] Apply DarkTheme for IdeaDetails and EditIdea dialogs
- [x] Apply Dark Theme to LATER and DONE ideas.
